server:
  port: 8501
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/db_spzx?characterEncoding=utf-8&serverTimezone=GMT%2B8

  data:
    redis:
      host: localhost
      port: 6379
      password:


mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode

  minio:
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: spzx-bucket
    endpoint: http://localhost:9000

